// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/UnicoYal/EventForge/internal/event_generator/config"
	"github.com/stretchr/testify/assert/yaml"
	"os"
)

// Injectors from wire.go:

func InitializeBox(configPath string) (*Box, error) {
	config, err := provideConfig(configPath)
	if err != nil {
		return nil, err
	}
	box := newBox(config)
	return box, nil
}

// wire.go:

func newBox(conf *config.Config) *Box {
	return &Box{
		Config: *conf,
	}
}

func provideConfig(configPath string) (*config.Config, error) {
	cfg := &config.Config{}

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("cannot read config file: %w", err)
	}

	if err = yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("cannot unmarshall config: %w", err)
	}

	return cfg, nil
}
