min_rate: 100
min_duration: 10s
dns_resolver: dns:///ingestion-headless.default.svc.cluster.local:50051
load_balance_policy: round_robin # pick_first/grpclb/xds/weighted_target/priority
event_type: default

worker_pool:
  size: 5000
  release_timeout: 2s